name: flashchat
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  modal_progress_hud_nsn: ^0.5.1
  image_picker: ^1.0.7
  firebase_storage: ^11.6.5
  google_sign_in: ^6.0.2
  sign_in_button: ^3.2.0
  firebase_messaging: ^14.7.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - images/