// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB90GLpeGzpc7kOB_KILvo7hx2buXdiMuY',
    appId: '1:875535465954:web:2ad92e3de1c50c06728dbb',
    messagingSenderId: '875535465954',
    projectId: 'flash-chat-c9269',
    authDomain: 'flash-chat-c9269.firebaseapp.com',
    databaseURL: 'https://flash-chat-c9269-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flash-chat-c9269.appspot.com',
    measurementId: 'G-WH3F3XLD0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoapJMiYWASA5XJEM4ZXqKF77lTAziI0s',
    appId: '1:875535465954:android:6f20306b4acb4b76728dbb',
    messagingSenderId: '875535465954',
    projectId: 'flash-chat-c9269',
    databaseURL: 'https://flash-chat-c9269-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flash-chat-c9269.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgVISh1ureefDceD5PHh-dzK8JW3W_O3w',
    appId: '1:875535465954:ios:2cc8e4450645a6a9728dbb',
    messagingSenderId: '875535465954',
    projectId: 'flash-chat-c9269',
    databaseURL: 'https://flash-chat-c9269-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flash-chat-c9269.appspot.com',
    iosClientId: '875535465954-1ormqp69tk248qn5ei3nk241jj1luftl.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgVISh1ureefDceD5PHh-dzK8JW3W_O3w',
    appId: '1:875535465954:ios:16caf2e6e1a54308728dbb',
    messagingSenderId: '875535465954',
    projectId: 'flash-chat-c9269',
    databaseURL: 'https://flash-chat-c9269-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flash-chat-c9269.appspot.com',
    iosClientId: '875535465954-ut7jinsf0djtvl82t16ra1vlu7e71b0s.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashchat.RunnerTests',
  );
}
